webtalk_init -webtalk_dir D:\\FPGA\\Z7010_MINI\\z7010_uart\\z7010_uart.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2024-07-25 22:39:41" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "s9qjmrl24rn918sfn5b5om2vl0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_18" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 5600X 6-Core Processor             " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3693 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.284 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1721905303695" -context "sdk\\\\bsp/1721905303695"
webtalk_add_data -client sdk -key hwid -value "1721904979339" -context "sdk\\\\bsp/1721905303695"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1721905303695"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1721905303695"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1721905303695"
webtalk_add_data -client sdk -key uid -value "1721905304724" -context "sdk\\\\application/1721905304724"
webtalk_add_data -client sdk -key hwid -value "1721904979339" -context "sdk\\\\application/1721905304724"
webtalk_add_data -client sdk -key bspid -value "1721905303695" -context "sdk\\\\application/1721905304724"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1721905304724"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1721905304724"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1721905304724"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1721905304724"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1721905304724"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1721905304724"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1721918381920"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1721918381920"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1721918381920"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1721918381920"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1721918381920"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1721918381920"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1721918381920"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1721918381920"
webtalk_transmit -clientid 429976631 -regid "" -xml D:\\FPGA\\Z7010_MINI\\z7010_uart\\z7010_uart.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\FPGA\\Z7010_MINI\\z7010_uart\\z7010_uart.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\FPGA\\Z7010_MINI\\z7010_uart\\z7010_uart.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
